# Generated by Django 4.2.16 on 2024-11-25 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ClothingItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("brand", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(max_length=20)),
                ("image", models.ImageField(blank=True, null=True, upload_to="clothing_items/")),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("last_worn", models.DateField(blank=True, null=True)),
                ("times_worn", models.PositiveIntegerField(default=0)),
                ("favorite", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="wardrobe.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("hex_code", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Outfit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("occasion", models.CharField(blank=True, max_length=50)),
                ("favorite", models.BooleanField(default=False)),
                ("times_worn", models.PositiveIntegerField(default=0)),
                ("last_worn", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("items", models.ManyToManyField(related_name="outfits", to="wardrobe.clothingitem")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outfits", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("items", models.ManyToManyField(blank=True, related_name="tags", to="wardrobe.clothingitem")),
                ("outfits", models.ManyToManyField(blank=True, related_name="tags", to="wardrobe.outfit")),
            ],
        ),
        migrations.AddField(
            model_name="outfit",
            name="seasons",
            field=models.ManyToManyField(related_name="outfits", to="wardrobe.season"),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="colors",
            field=models.ManyToManyField(related_name="items", to="wardrobe.color"),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="clothing_items", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="seasons",
            field=models.ManyToManyField(related_name="items", to="wardrobe.season"),
        ),
    ]
